"""Cliente de MeteoGalicia sin dependencias de Home Assistant."""

from .chimere import ChimereClient
from .client import MeteoGalClient
from .exceptions import (
    MeteoGalConnectionError,
    MeteoGalError,
    MeteoGalNotFoundError,
    MeteoGalResponseError,
    MeteoSixAuthError,
    MeteoSixError,
)
from .meteosix import MeteoSixClient
from .models import (
    AirDayForecast,
    AirIndex,
    AirMeasurements,
    AirModelHour,
    AirStation,
    AirStationIndex,
    Camera,
    Concello,
    ConcelloObservation,
    DailyForecast,
    DayParts,
    HourlyForecast,
    MediumTermForecast,
    MeteoSixHour,
    SkyProbability,
    Station,
    StationDay,
    StationReading,
    WeatherWarning,
)

__all__ = [
    "AirDayForecast",
    "AirIndex",
    "AirMeasurements",
    "AirModelHour",
    "AirStation",
    "AirStationIndex",
    "Camera",
    "ChimereClient",
    "Concello",
    "ConcelloObservation",
    "DailyForecast",
    "DayParts",
    "HourlyForecast",
    "MediumTermForecast",
    "MeteoGalClient",
    "MeteoGalConnectionError",
    "MeteoGalError",
    "MeteoGalNotFoundError",
    "MeteoGalResponseError",
    "MeteoSixAuthError",
    "MeteoSixClient",
    "MeteoSixError",
    "MeteoSixHour",
    "SkyProbability",
    "Station",
    "StationDay",
    "StationReading",
    "WeatherWarning",
]
